"use client";
import { useTransition } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { employeeSchema } from "@/lib/validation/employee";
import { z } from "zod";
import { createEmployee, updateEmployee } from "@/app/actions/employees";
import { useRouter } from "next/navigation";
type EmployeeFormValues = z.infer<typeof employeeSchema>;
type Option = { id: string; name: string };
export function EmployeeForm({ employee, teams, countries }: { employee?: Partial<EmployeeFormValues> & { id?: string }; teams: Option[]; countries: Option[] }) {
  const router = useRouter(); const [isPending, startTransition] = useTransition();
  const form = useForm<EmployeeFormValues>({ resolver: zodResolver(employeeSchema), defaultValues: { name: employee?.name ?? "", email: employee?.email ?? "", title: employee?.title ?? "", countryId: employee?.countryId ?? "", teamIds: employee?.teamIds ?? [], notes: employee?.notes ?? "", status: employee?.status ?? "ACTIVE" } });
  const selectedTeamIds = new Set(form.watch("teamIds"));
  async function onSubmit(values: EmployeeFormValues) { startTransition(async () => { if (employee?.id) { await updateEmployee(employee.id, values); router.push(`/employees/${employee.id}`); } else { const created = await createEmployee(values); router.push(`/employees/${created.id}`); } router.refresh(); }); }
  return <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6"><div className="grid gap-4 md:grid-cols-2"><div><label className="mb-2 block text-sm font-medium">Employee name</label><input className="w-full rounded-xl border px-3 py-2" {...form.register("name")} /><p className="mt-1 text-xs text-red-600">{form.formState.errors.name?.message}</p></div><div><label className="mb-2 block text-sm font-medium">Email</label><input className="w-full rounded-xl border px-3 py-2" {...form.register("email")} /><p className="mt-1 text-xs text-red-600">{form.formState.errors.email?.message}</p></div></div><div className="grid gap-4 md:grid-cols-3"><div><label className="mb-2 block text-sm font-medium">Title</label><input className="w-full rounded-xl border px-3 py-2" {...form.register("title")} /></div><div><label className="mb-2 block text-sm font-medium">Country</label><select className="w-full rounded-xl border px-3 py-2" {...form.register("countryId")}><option value="">Unassigned</option>{countries.map((country) => <option key={country.id} value={country.id}>{country.name}</option>)}</select></div><div><label className="mb-2 block text-sm font-medium">Status</label><select className="w-full rounded-xl border px-3 py-2" {...form.register("status")}><option value="ACTIVE">Active</option><option value="ARCHIVED">Archived</option></select></div></div><div><label className="mb-2 block text-sm font-medium">Teams</label><div className="grid gap-2 md:grid-cols-3">{teams.map((team) => { const checked = selectedTeamIds.has(team.id); return <label key={team.id} className="flex items-center gap-2 rounded-xl border p-3 text-sm"><input type="checkbox" checked={checked} onChange={(e) => { const current = form.getValues("teamIds"); form.setValue("teamIds", e.target.checked ? [...current, team.id] : current.filter((id) => id !== team.id), { shouldValidate: true }); }} />{team.name}</label>; })}</div></div><div><label className="mb-2 block text-sm font-medium">Notes</label><textarea className="min-h-24 w-full rounded-xl border px-3 py-2" {...form.register("notes")} /></div><div className="flex items-center justify-end gap-3"><button type="button" className="rounded-xl border px-4 py-2" onClick={() => router.back()}>Cancel</button><button disabled={isPending} className="rounded-xl bg-slate-900 px-4 py-2 text-white">{isPending ? "Saving..." : employee?.id ? "Save changes" : "Create employee"}</button></div></form>;
}
