import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { getNativeMonthlyCost, getNativeAnnualCost, getSeatStats } from "@/lib/calculations/costs";
import { formatMoney, formatDate } from "@/lib/format";
import { VendorAssignmentPanel } from "@/components/assignments/vendor-assignment-panel";
export default async function VendorDetailPage({ params }: { params: { id: string } }) {
  const [vendor, employees] = await Promise.all([
    db.vendor.findUnique({ where: { id: params.id }, include: { owner: true, tags: { include: { tag: true } }, assignments: { include: { employee: { include: { country: true, teams: { include: { team: true } } } } } } } }),
    db.employee.findMany({ where: { status: "ACTIVE" }, include: { teams: { include: { team: true } }, assignments: true }, orderBy: { name: "asc" } })
  ]);
  if (!vendor) notFound();
  const seats = getSeatStats(vendor); const activeEmployeeIds = new Set(vendor.assignments.filter((a) => a.status === "ACTIVE").map((a) => a.employeeId));
  return <div className="space-y-6"><div className="flex items-start justify-between"><div><h2 className="text-2xl font-semibold">{vendor.name}</h2><p className="text-sm text-slate-500">{vendor.tags.map((t) => t.tag.name).join(", ")}</p></div><Link href={`/vendors/${vendor.id}/edit`} className="rounded-xl border px-4 py-2 text-sm">Edit Vendor</Link></div><div className="grid gap-4 md:grid-cols-4"><div className="rounded-2xl border bg-white p-4"><div className="text-sm text-slate-500">Native Monthly</div><div className="mt-2 text-xl font-semibold">{formatMoney(getNativeMonthlyCost(vendor), vendor.nativeCurrency)}</div></div><div className="rounded-2xl border bg-white p-4"><div className="text-sm text-slate-500">Native Annual</div><div className="mt-2 text-xl font-semibold">{formatMoney(getNativeAnnualCost(vendor), vendor.nativeCurrency)}</div></div><div className="rounded-2xl border bg-white p-4"><div className="text-sm text-slate-500">Seats Assigned</div><div className="mt-2 text-xl font-semibold">{seats.seatsAssigned}</div></div><div className="rounded-2xl border bg-white p-4"><div className="text-sm text-slate-500">Seats Remaining</div><div className="mt-2 text-xl font-semibold">{seats.seatsRemaining}</div></div></div><div className="grid gap-6 lg:grid-cols-[1fr_1.1fr]"><div className="rounded-2xl border bg-white p-5"><h3 className="mb-4 font-semibold">Vendor Details</h3><dl className="space-y-3 text-sm"><div className="flex justify-between gap-4"><dt className="text-slate-500">Owner</dt><dd>{vendor.owner?.name ?? "—"}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Billing Type</dt><dd>{vendor.billingType}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Billing Cadence</dt><dd>{vendor.billingCadence}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Renewal Date</dt><dd>{formatDate(vendor.renewalDate)}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Allocation Mode</dt><dd>{vendor.allocationMode}</dd></div></dl></div><VendorAssignmentPanel vendorId={vendor.id} employees={employees.map((employee) => ({ id: employee.id, name: employee.name, email: employee.email, teamNames: employee.teams.map((t) => t.team.name), assigned: activeEmployeeIds.has(employee.id) }))} /></div></div>;
}
