export const dynamic = "force-dynamic";

import { getDashboardData } from "@/lib/queries/dashboard";
import { formatMoney, formatDate } from "@/lib/format";
export default async function DashboardPage() {
  const data = await getDashboardData("EUR");
  const renewals = data.rows.filter((row) => row.renewalDate).sort((a, b) => new Date(a.renewalDate!).getTime() - new Date(b.renewalDate!).getTime()).slice(0, 8);
  return <div className="space-y-8"><div><h2 className="text-2xl font-semibold">Dashboard</h2><p className="text-sm text-slate-500">Overview of software spend, seat usage, and renewals.</p></div><div className="grid gap-4 md:grid-cols-4"><div className="rounded-2xl border bg-white p-5"><div className="text-sm text-slate-500">Monthly Spend</div><div className="mt-2 text-2xl font-semibold">{formatMoney(data.totals.monthly, data.reportingCurrency)}</div></div><div className="rounded-2xl border bg-white p-5"><div className="text-sm text-slate-500">Annual Spend</div><div className="mt-2 text-2xl font-semibold">{formatMoney(data.totals.annual, data.reportingCurrency)}</div></div><div className="rounded-2xl border bg-white p-5"><div className="text-sm text-slate-500">Active Vendors</div><div className="mt-2 text-2xl font-semibold">{data.rows.length}</div></div><div className="rounded-2xl border bg-white p-5"><div className="text-sm text-slate-500">Over-assigned Vendors</div><div className="mt-2 text-2xl font-semibold">{data.rows.filter((r) => r.seatStats.seatOverage > 0).length}</div></div></div><div className="grid gap-6 lg:grid-cols-[2fr_1fr]"><div className="rounded-2xl border bg-white p-5"><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold">Vendor Cost Overview</h3><span className="text-sm text-slate-500">Reporting currency: {data.reportingCurrency}</span></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="pb-3">Vendor</th><th className="pb-3">Owner</th><th className="pb-3">Monthly</th><th className="pb-3">Annual</th><th className="pb-3">Assigned</th><th className="pb-3">Purchased</th></tr></thead><tbody>{data.rows.map((row) => <tr key={row.id} className="border-b last:border-0"><td className="py-3 font-medium">{row.name}</td><td className="py-3">{row.owner?.name ?? "—"}</td><td className="py-3">{formatMoney(row.normalizedMonthly, data.reportingCurrency)}</td><td className="py-3">{formatMoney(row.normalizedAnnual, data.reportingCurrency)}</td><td className="py-3">{row.seatStats.seatsAssigned}</td><td className="py-3">{row.seatStats.seatsPurchased}</td></tr>)}</tbody></table></div></div><div className="rounded-2xl border bg-white p-5"><h3 className="mb-4 font-semibold">Upcoming Renewals</h3><div className="space-y-3">{renewals.map((item) => <div key={item.id} className="rounded-xl border p-3"><div className="font-medium">{item.name}</div><div className="text-sm text-slate-500">{formatDate(item.renewalDate)}</div></div>)}</div></div></div></div>;
}
